team_dict = {
    0: 'No Team',
    2: 'Celtics',
    17: 'Nets',
    18: 'Knicks',
    20: '76ers',
    28: 'Raptors',
    4: 'Bulls',
    5: 'Cavaliers',
    8: 'Pistons',
    11: 'Pacers',
    15: 'Bucks',
    1: 'Hawks',
    30: 'Hornets',
    14: 'Heat',
    19: 'Magic',
    27: 'Wizards',
    7: 'Nuggets',
    16: 'Timberwolves',
    25: 'Thunder',
    22: 'Trail Blazers',
    26: 'Jazz',
    9: 'Warriors',
    12: 'Clippers',
    13: 'Lakers',
    21: 'Suns',
    23: 'Kings',
    6: 'Mavericks',
    10: 'Rockets',
    29: 'Grizzlies',
    3: 'Pelicans',
    24: 'Spurs'
}